repos:
-   repo: local
    hooks:
      -   id: sqlfluff-lint
          name: Проверка правил написания запросов для моделей
          entry: sqlfluff lint
          language: system
          files: \.sql$
          args: ["--config", ".sqlfluff"]
      -   id: sqlfluff-fix
          name: Исправление запросов для моделей
          entry: sqlfluff fix
          language: system
          files: \.sql$
          args: ["--config", ".sqlfluff", "--force"]
    