name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

clean-targets:         # директории, которые будут очищаться при dbt clean
  - "target"
  - "dbt_packages"

# Конфигурация моделей
# Полная документация: https://docs.getdbt.com/docs/configuring-models

vars:
  "dbt_date:time_zone": "Europe/Moscow"

models:
  dbt_project:
    +materialized: table # все модели по умолчанию материализуются в таблицы
    +persist_docs:
      relation: true
      columns: true
    scripts:
      ods:
        +schema: ods
      cdm:
        +schema: cdm
      dm:
        +schema: dm
      service:
        +schema: service
seeds:
  dbt_project:
    schema: seeds