name: DBT Project Workflow
on:
  push:
    branches: [main]
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout repository code
        uses: actions/checkout@v5

      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: install dependencies
        run: uv sync --locked

      - name: prepare connection profile
        run: cp profiles.example.yml profiles.yml

      - name: install dbt packages
        run: uv run dbt deps

      - name: generate dbt docs
        run: uv run dbt docs generate
        env:
          DBT_ENV_SECRET_NAME: ${{ secrets.DB_NAME }}
          DBT_ENV_SECRET_HOST: ${{ secrets.DB_HOST }}
          DBT_ENV_SECRET_PASS: ${{ secrets.DB_PASS }}
          DBT_ENV_SECRET_USER: ${{ secrets.DB_USER }}

      - name: prepare site
        run: |
          mkdir data_catalog
          cp target/index.html data_catalog/
          cp target/manifest.json data_catalog/
          cp target/catalog.json data_catalog/

      - name: generage data catalog
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data_catalog
          publish_branch: data_catalog_branch

